# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_name', models.CharField(max_length=100)),
                ('ring_region', models.CharField(max_length=10)),
                ('ne_name', models.CharField(max_length=100)),
                ('ne_type', models.CharField(max_length=10)),
            ],
        ),
    ]
