# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('edge_weight', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Ring',
            new_name='NetworkElement',
        ),
    ]
