# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_auto_20160508_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiberrelationship',
            name='edge_weight',
            field=models.IntegerField(),
        ),
    ]
