# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0003_auto_20160508_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkelement',
            name='ne_type',
            field=models.CharField(max_length=100),
        ),
    ]
