# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0004_auto_20160510_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiberrelationship',
            name='edge_weight',
            field=models.CharField(max_length=100),
        ),
    ]
