# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0007_arp_arr_bar_bcne_dr_lsc_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
    ]
