# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0008_errormsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arp',
            name='arp',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='arr',
            name='arr_ne',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bar',
            name='bar_ne',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lsc',
            name='lsc_ne',
            field=models.TextField(max_length=1000),
        ),
    ]
