# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0009_auto_20160629_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='errormsg',
            name='ring_name',
            field=models.CharField(default=datetime.datetime(2016, 6, 29, 9, 33, 42, 97000, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
