# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0011_detailresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ARP',
        ),
        migrations.DeleteModel(
            name='ARR',
        ),
        migrations.DeleteModel(
            name='BAR',
        ),
        migrations.DeleteModel(
            name='BCNE',
        ),
        migrations.DeleteModel(
            name='DR',
        ),
        migrations.DeleteModel(
            name='ErrorMsg',
        ),
        migrations.DeleteModel(
            name='LSC',
        ),
    ]
